import pytest

from smiles_to_iupac import smiles_to_iupac
from smiles_to_iupac._common import UnsupportedStructure


@pytest.mark.parametrize(
    "smiles,expected",
    [
        # Simplest cases, cross-checked against PubChem PUG REST
        # (compound/smiles/<smiles>/property/IUPACName).
        ("CO", "methanol"),
        ("CCO", "ethanol"),
        # P-14.3.4.2 style locant choice for a real positional choice:
        # 'propan-1-ol' vs 'propan-2-ol', both cross-checked against PubChem.
        ("CCCO", "propan-1-ol"),
        ("CC(O)C", "propan-2-ol"),
        # Diol / triol: multiplying prefix + full locant set, both
        # cross-checked against PubChem (glycol/glycerol's systematic names).
        ("OCCO", "ethane-1,2-diol"),
        ("OCC(O)CO", "propane-1,2,3-triol"),
        # P-16.3.3 multiplying-prefix elision: 'tetra'/'penta'/'hexa'
        # elide their terminal 'a' before the vowel-initial 'ol' suffix
        # ('tetrol'/'pentol'/'hexol', not 'tetraol'/'pentaol'/'hexaol').
        # Cross-checked against PubChem PUG REST IUPACName: CID 8998
        # (butane-1,2,3,4-tetrol), CID 827 (pentane-1,2,3,4,5-pentol),
        # CID 453 (hexane-1,2,3,4,5,6-hexol).
        ("OCC(O)C(O)CO", "butane-1,2,3,4-tetrol"),
        ("OCC(O)C(O)C(O)CO", "pentane-1,2,3,4,5-pentol"),
        ("OCC(O)C(O)C(O)C(O)CO", "hexane-1,2,3,4,5,6-hexol"),
        # Monocyclic saturated ring, single -OH: P-14.3.3 locant omission
        # (like 'methylcyclohexane') applies to the suffix too. Cross-checked
        # against PubChem.
        ("OC1CCCCC1", "cyclohexanol"),
        # -OH combined with existing unsaturation support, on carbons that
        # don't touch the double bond (avoiding the enol guard). Cross-
        # checked against PubChem: the -OH gets locant 1 (suffix priority,
        # P-44.4.1.8) even though numbering from the other end would give
        # the double bond locant 1 instead.
        ("OCCCC=C", "pent-4-en-1-ol"),
        # -OH combined with a halogen substituent prefix, on a chain long
        # enough (3 carbons) that the P-14.3.4.2(b) short-chain omission
        # never applies, sidestepping the ambiguous two-carbon case (see
        # module docstring). Cross-checked against PubChem.
        ("OCCCCl", "3-chloropropan-1-ol"),
        ("OCC(F)CC", "2-fluorobutan-1-ol"),
        # -OH + halogen together on a ring: suffix locant priority
        # (P-44.4.1.8) fixes C1 at the -OH carbon, then the halogen gets the
        # lowest remaining locant. Cross-checked against PubChem.
        ("OC1CCCCC1Cl", "2-chlorocyclohexan-1-ol"),
        # A plain, unsubstituted ring bearing no -OH of its own, with the
        # -OH on a chain hanging off the ring instead: the chain (not the
        # ring) is the parent, and the ring is cited as a "cyclo..."
        # substituent prefix (tasks/ring-substituent-chain-suffix.md,
        # 2026-08-25). Mononuclear (one-carbon) chain, so P-14.3.4.2(a)
        # omits the -OH locant same as plain 'methanol' -- cross-checked
        # against PubChem CID 7507 ("Cyclohexylmethanol").
        ("OCC1CCCCC1", "cyclohexylmethanol"),
        # Same shape, two-carbon chain. This falls into the same
        # already-documented ambiguous case as '2-chloroethanol' above (see
        # module docstring's P-14.3.4.2(a)/(b) note): PubChem's own
        # autogenerated name for this exact SMILES ('2-cyclohexylethanol')
        # omits the -OH locant, but this module deliberately always cites
        # it once the single-substituent omission precondition fails
        # (consistent with the halogen case already handled the same way),
        # so this is an accepted, reviewed result rather than a PubChem-
        # confirmed one.
        ("OCCC1CCCCC1", "2-cyclohexylethan-1-ol"),
        # A single specified tetrahedral stereocenter (P-92,
        # tasks/rs-stereocenter-naming.md, 2026-08-25): the Blue Book's own
        # worked example for this exact suffix, cross-checked against
        # PubChem CID 84682/444683 for the two enantiomers.
        ("C[C@@H](O)CC", "(2R)-butan-2-ol"),
        ("C[C@H](O)CC", "(2S)-butan-2-ol"),
        # A specified stereocenter combined with existing ene-suffix
        # support: the Blue Book's other own worked example for this
        # suffix, cross-checked against PubChem CID 6994331.
        ("C=C[C@H](O)CC", "(3R)-pent-1-en-3-ol"),
        # Two specified stereocenters (P-92/P-91.3,
        # tasks/multi-stereocenter-naming.md, 2026-08-26): ascending-locant,
        # comma-separated citation in one parenthesized group -- both
        # diastereomers cross-checked against PubChem CID 12575191/11389370.
        ("C[C@H]([C@@H](C)Cl)O", "(2R,3R)-3-chlorobutan-2-ol"),
        ("C[C@H]([C@H](C)Cl)O", "(2R,3S)-3-chlorobutan-2-ol"),
        # A genuine stereocenter left *unspecified* in the input (no
        # `@`/`@@`) is not a new rejection case -- it's named exactly as
        # before (no stereodescriptor), matching both this project's prior
        # behavior and PubChem's own convention for a name that doesn't
        # specify configuration at all.
        ("CC(O)CC", "butan-2-ol"),
    ],
)
def test_alcohol_names(smiles, expected):
    assert smiles_to_iupac(smiles) == expected


def test_multiple_stereocenters_supported():
    # 3-methylpentan-2-ol, two specified stereocenters -- PubChem-verified
    # exactly for this SMILES ('(2S,3R)-3-methylpentan-2-ol', CID 6993006).
    assert smiles_to_iupac("C[C@H](O)[C@H](C)CC") == "(2S,3R)-3-methylpentan-2-ol"


def test_stereocenter_with_ez_double_bond_raises():
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("C[C@H](O)/C=C/C")


def test_partially_specified_stereocenters_raises():
    # one specified, one left unspecified -- an ambiguous mix, not the
    # same as "no stereo specified at all".
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("C[C@H](O)C(C)CC")


def test_ring_stereocenter_raises():
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("O[C@H]1CCCCC1C")


def test_three_stereocenters_supported():
    # Three specified stereocenters on one chain: not independently found
    # on PubChem, but the prefix-joining logic this exercises (sorting by
    # locant, comma-joining N pairs) is a simple, directly-inspectable
    # generalization of the already-verified two-stereocenter case above,
    # and CIP computation itself is fully delegated to RDKit, not
    # reimplemented -- a reviewed, not independently confirmed, result.
    assert smiles_to_iupac("CC[C@H](C)[C@@H](Cl)[C@H](C)O") == "(2S,3R,4S)-3-chloro-4-methylhexan-2-ol"


def test_pseudoasymmetric_stereocenter_raises():
    # pentane-2,3,4-triol built with the outer two centers as mirror
    # images of each other: RDKit's rdCIPLabeler assigns the middle center
    # a lowercase 'r' (pseudoasymmetric), out of scope here (see
    # tasks/multi-stereocenter-naming.md's exclusions) -- this project
    # doesn't attempt to verify pseudoasymmetric CIP assignment itself.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("C[C@@H](O)[C@H](O)[C@@H](O)C")




def test_ring_with_own_hydroxyl_and_chain_hydroxyl():
    # the ring bears exactly one -OH *and* a single unbranched chain
    # substituent also bears exactly one -OH: a genuine P-44.1.2.2 tie
    # (both candidate parents capture exactly one -OH), which P-44.1.2.2
    # always resolves in the ring's favor. Cross-checked against PubChem
    # PUG REST: CID 5175258 (OC1CCCCC1CO) ->
    # "2-(hydroxymethyl)cyclohexan-1-ol".
    assert smiles_to_iupac("OC1CCCCC1CO") == "2-(hydroxymethyl)cyclohexan-1-ol"


def test_tetrasubstituted_ring_atom_with_own_hydroxyl_and_chain_hydroxyl():
    # the same ring carbon carries both the ring's own -OH and the
    # OH-bearing chain branch. Cross-checked against PubChem PUG REST:
    # CID 251259 (OC1(CO)CCCCC1) -> "1-(hydroxymethyl)cyclohexan-1-ol".
    assert smiles_to_iupac("OC1(CO)CCCCC1") == "1-(hydroxymethyl)cyclohexan-1-ol"


def test_ring_hydroxyl_count_exceeds_chain():
    # the ring has two -OH's, the chain has one: P-44.1.1's principal-group
    # count settles it outright in the ring's favor (no tie needed).
    # Cross-checked against PubChem PUG REST: CID 18944701
    # (OC1C(O)CC(CO)CC1) -> "4-(hydroxymethyl)cyclohexane-1,2-diol".
    assert smiles_to_iupac("OC1C(O)CC(CO)CC1") == "4-(hydroxymethyl)cyclohexane-1,2-diol"


def test_ring_hydroxyl_count_exceeds_chain_by_two():
    # CID 22311515 (OC1C(O)C(O)C(CO)CC1) ->
    # "4-(hydroxymethyl)cyclohexane-1,2,3-triol".
    assert smiles_to_iupac("OC1C(O)C(O)C(CO)CC1") == "4-(hydroxymethyl)cyclohexane-1,2,3-triol"


def test_equal_hydroxyl_counts_above_one_each():
    # ring and chain both have two -OH's: still a tie, resolved in the
    # ring's favor the same way as the one-each tie above. CID 22670583
    # (OC1C(O)CC(C(O)CO)CC1) -> "4-(1,2-dihydroxyethyl)cyclohexane-1,2-diol".
    assert smiles_to_iupac("OC1C(O)CC(C(O)CO)CC1") == "4-(1,2-dihydroxyethyl)cyclohexane-1,2-diol"


def test_chain_hydroxyl_count_exceeds_ring_now_supported():
    # the chain has more -OH's than the ring (two vs. one): the chain is
    # now the senior parent (P-44.1.1) and the ring, with its own single
    # -OH, is cited as a substituent (as of
    # tasks/ring-substituent-own-hydroxyl-naming.md, 2026-08-26).
    # PubChem-verified exactly (CID 130142401).
    assert smiles_to_iupac("OC1CCCCC1C(O)CO") == "1-(2-hydroxycyclohexyl)ethane-1,2-diol"


def test_chain_hydroxyl_count_exceeds_ring_with_no_ring_hydroxyl_chain():
    # the ring's own -OH, chain has none besides -- exercises
    # `_ring_substituent_with_hydroxyl` via the plain
    # `_name_ring_substituent_chain_alcohol` path (ring bears an -OH but
    # the chain substituent doesn't compete for the suffix at all, so the
    # ring is simply the sole -OH-bearing parent, unaffected by this
    # task's new ring-vs-chain wiring).
    assert smiles_to_iupac("OC1CCC(CC)CC1") == "4-ethylcyclohexan-1-ol"


def test_ring_with_two_hydroxyls_outcompeted_by_chain_raises():
    # the ring has two of its own -OH's, but the chain has three -- still
    # unsupported, since `name_branch`'s ring-substituent machinery only
    # expresses a single ring hydroxyl (see tasks/pin-selection-and-parent-
    # choice.md's remaining scope).
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OC1C(O)CCC(C(O)C(O)CO)C1")


def test_substituted_ring_with_chain_hydroxyl_raises():
    # the ring itself carries an extra substituent (not just the OH-bearing
    # chain) -- out of this module's minimal scope.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OCC1CCCCC1C")


def test_branched_chain_hydroxyl_on_ring_raises():
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OCC(C)C1CCCCC1")


def test_carboxylic_acid_not_misread_as_alcohol():
    # -C(=O)-OH: a carboxylic acid is a more senior characteristic group
    # (Table 3.3) than a plain alcohol; must not be misread as one (it's
    # routed to the dedicated carboxylic-acid module instead, see
    # test_carboxylic_acid.py).
    assert smiles_to_iupac("CC(=O)O") == "ethanoic acid"


def test_ketone_hetero_mix_dispatches_to_ketone_module():
    # A structure with both -OH and a ketone C=O: 'one' outranks 'ol' in
    # Table 3.3, so the ketone module (see test_ketone.py) names it with
    # 'hydroxy' as a substituent prefix instead of this module's own suffix.
    assert smiles_to_iupac("OCC(=O)C") == "1-hydroxypropan-2-one"


def test_aldehyde_alcohol_mix_dispatches_to_aldehyde_module():
    # A structure with both -OH and an aldehyde-shaped carbonyl: 'al'
    # outranks 'ol' in Table 3.3, so the aldehyde module (see
    # test_aldehyde.py) names it with 'hydroxy' as a substituent prefix
    # instead of this module's own suffix.
    assert smiles_to_iupac("OCC=O") == "2-hydroxyethanal"


def test_phenol_raises():
    # An aromatic ring bearing -OH is out of scope for this module (separate,
    # in-progress aromatic-ring module's territory); must not be picked up
    # here before reaching that module.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("Oc1ccccc1")


def test_bicyclic_alcohol_raises():
    # Same skeleton as test_halogens.py's 'ClC1CC2CCC1CC2' ->
    # '2-chlorobicyclo[2.2.2]octane', with the halogen swapped for -OH: a
    # real, nameable compound ('bicyclo[2.2.2]octan-2-ol', confirmed via
    # PubChem), but von Baeyer polycyclic alcohols are explicitly deferred.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OC1CC2CCC1CC2")


def test_ether_raises():
    # An ether coexisting with a hydroxyl (as opposed to a plain ether on
    # its own, now handled by the separate ether module) is still out of
    # scope for this module.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OCCOCC")


def test_enol_raises():
    # -OH on a carbon that is also part of a C=C bond: deliberately
    # narrowed out of scope (see module docstring).
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OC=CC")


def test_amine_hetero_mix_raises():
    # A structure with both -OH and a non-halogen heteroatom (N) is rejected
    # outright by the alcohol module; this module never attempts
    # suffix-vs-suffix seniority competition (Table 3.3) since only
    # C/O(-OH)/halogen atoms are accepted at all. (A pure amine, no -OH, is
    # dispatched to the separate amine module instead — see test_amine.py.)
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OCCN")
