import pytest

from smiles_to_iupac import smiles_to_iupac
from smiles_to_iupac._common import UnsupportedStructure


@pytest.mark.parametrize(
    "smiles,expected",
    [
        # cross-checked against PubChem PUG REST IUPACName:
        # CID 68973 (CP), CID 69607 (CPC), CID 136382 (CCP),
        # CID 68983 (CP(C)C), CID 27365 (CCP(CC)CC), CID 20221924 (CCPC),
        # CID 535207 (CCP(C)C), CID 13836128 (CCP(CC)C).
        ("CP", "methylphosphane"),
        ("CPC", "dimethylphosphane"),
        ("CCP", "ethylphosphane"),
        ("CP(C)C", "trimethylphosphane"),
        ("CCP(CC)CC", "triethylphosphane"),
        ("CCPC", "ethyl(methyl)phosphane"),
        # three different substituents: PubChem's own autogenerated name
        # ("ethyl-methyl-propylphosphane") does not follow the Blue Book's
        # own published errata rule (P-16.5.1.3.1, parenthesize every
        # substituent after the alphabetically first when locants are
        # omitted) -- applying that rule directly instead, cross-checked
        # against the analogous silane errata example
        # "butyl(ethyl)(methyl)(propyl)silane".
        ("CCP(C)CCC", "ethyl(methyl)(propyl)phosphane"),
        # a multiply-cited substituent mixed with a different one: each
        # distinct name gets its own multiplying prefix by count, and the
        # alphabetically-first name is still the only one never
        # parenthesized, regardless of its own count -- but the
        # multiplying prefix itself sits *outside* the parentheses (Blue
        # Book "ethyldi(methyl)phosphane (PIN)" worked example,
        # `tmp/bluebook/P1.html`), not PubChem's own raw
        # "ethyl(dimethyl)phosphane" for CID 535207's structure.
        ("CCP(C)C", "ethyldi(methyl)phosphane"),
        ("CCP(CC)C", "diethyl(methyl)phosphane"),
        # halogen bonded directly to phosphorus: structure cross-checked
        # against PubChem PUG REST, CID 161938 (ClP), CID 13128761
        # (ClPCl), CID 69936 (ClP(C)C) -- the last name matches the Blue
        # Book's own "chlorodi(methyl)borane (PIN)" analogue
        # (`tmp/bluebook/P6.txt`), not PubChem's own raw
        # "chloro(dimethyl)phosphane".
        ("ClP", "chlorophosphane"),
        ("ClPCl", "dichlorophosphane"),
        ("ClP(C)C", "chlorodi(methyl)phosphane"),
    ],
)
def test_smiles_to_iupac_simple_phosphane(smiles, expected):
    assert smiles_to_iupac(smiles) == expected


def test_halogen_substituted_alkyl_chain_raises():
    # a halogen embedded partway along a carbon chain (rather than bonded
    # directly to phosphorus) is out of scope for this module.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("ClCCP")


@pytest.mark.parametrize(
    "smiles,expected",
    [
        # PubChem-verified: CID 537979, 123165.
        ("CC(C)P", "propan-2-ylphosphane"),
        ("CC(C)(C)P", "tert-butylphosphane"),
        # CID 20566651: position-based parens for the non-first substituent.
        ("CC(C)PC", "methyl(propan-2-yl)phosphane"),
        # PubChem's own raw name for this structure (CID 85572629) is
        # "propan-2-yl(propyl)phosphane" (no parens on the first term),
        # but P-16.5.1.3.1's literal text ("the first cited substituent
        # never has enclosing marks unless it is a compound substituent
        # group or includes a locant") requires parentheses here too --
        # another instance of PubChem omitting parentheses this project's
        # own PIN convention requires (see e.g. `_azide.py`/`_ether.py`'s
        # benzene-ring paths).
        ("CC(C)P(CCC)", "(propan-2-yl)(propyl)phosphane"),
        # CID 80969: multiplied compound name needs its own parens.
        ("CC(C)P(C(C)C)C(C)C", "tri(propan-2-yl)phosphane"),
    ],
)
def test_branched_substituent(smiles, expected):
    assert smiles_to_iupac(smiles) == expected


def test_multiplied_compound_substituent_with_different_substituent_raises():
    # Unconfirmed punctuation for this combination (see module/
    # `format_mononuclear_prefixes` docstrings) -- deliberately out of
    # scope rather than guessed.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("CCCP(C(C)C)C(C)C")


def test_unsaturated_substituent_raises():
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("C=CP")
