import pytest

from smiles_to_iupac import smiles_to_iupac
from smiles_to_iupac._common import UnsupportedStructure


@pytest.mark.parametrize(
    "smiles,expected",
    [
        # Simplest cases, cross-checked against PubChem PUG REST
        # (compound/smiles/<smiles>/property/IUPACName).
        ("CO", "methanol"),
        ("CCO", "ethanol"),
        # P-14.3.4.2 style locant choice for a real positional choice:
        # 'propan-1-ol' vs 'propan-2-ol', both cross-checked against PubChem.
        ("CCCO", "propan-1-ol"),
        ("CC(O)C", "propan-2-ol"),
        # Diol / triol: multiplying prefix + full locant set, both
        # cross-checked against PubChem (glycol/glycerol's systematic names).
        ("OCCO", "ethane-1,2-diol"),
        ("OCC(O)CO", "propane-1,2,3-triol"),
        # P-16.3.3 multiplying-prefix elision: 'tetra'/'penta'/'hexa'
        # elide their terminal 'a' before the vowel-initial 'ol' suffix
        # ('tetrol'/'pentol'/'hexol', not 'tetraol'/'pentaol'/'hexaol').
        # Cross-checked against PubChem PUG REST IUPACName: CID 8998
        # (butane-1,2,3,4-tetrol), CID 827 (pentane-1,2,3,4,5-pentol),
        # CID 453 (hexane-1,2,3,4,5,6-hexol).
        ("OCC(O)C(O)CO", "butane-1,2,3,4-tetrol"),
        ("OCC(O)C(O)C(O)CO", "pentane-1,2,3,4,5-pentol"),
        ("OCC(O)C(O)C(O)C(O)CO", "hexane-1,2,3,4,5,6-hexol"),
        # Monocyclic saturated ring, single -OH: P-14.3.3 locant omission
        # (like 'methylcyclohexane') applies to the suffix too. Cross-checked
        # against PubChem.
        ("OC1CCCCC1", "cyclohexanol"),
        # Monocyclic ring, single -OH, single ring double bond (P-31.1.3):
        # the hydroxyl always gets locant 1 (suffix priority), the ring
        # double bond's locant is minimized by choosing direction.
        # Cross-checked against PubChem (CID 13198/556685).
        ("OC1CCCC=C1", "cyclohex-2-en-1-ol"),
        ("OC1CC=CCC1", "cyclohex-3-en-1-ol"),
        # myo-inositol (a cyclitol, P-104): its PIN is not a trivial name
        # but the fully-substitutive "cyclohexane-1,2,3,4,5,6-hexol" --
        # already reachable via this module's existing ring-polyol support
        # plus the P-16.3.3 elision fix above (this used to render as the
        # one-letter-wrong "-hexaol"). Cross-checked against PubChem CID
        # 892 (stereo-free skeleton, since full stereo descriptors for six
        # ring stereocenters are still out of scope).
        ("OC1C(O)C(O)C(O)C(O)C1O", "cyclohexane-1,2,3,4,5,6-hexol"),
        # -OH combined with existing unsaturation support, on carbons that
        # don't touch the double bond (avoiding the enol guard). Cross-
        # checked against PubChem: the -OH gets locant 1 (suffix priority,
        # P-44.4.1.8) even though numbering from the other end would give
        # the double bond locant 1 instead.
        ("OCCCC=C", "pent-4-en-1-ol"),
        # -OH combined with a halogen substituent prefix, on a chain long
        # enough (3 carbons) that the P-14.3.4.2(b) short-chain omission
        # never applies, sidestepping the ambiguous two-carbon case (see
        # module docstring). Cross-checked against PubChem.
        ("OCCCCl", "3-chloropropan-1-ol"),
        ("OCC(F)CC", "2-fluorobutan-1-ol"),
        # -OH + halogen together on a ring: suffix locant priority
        # (P-44.4.1.8) fixes C1 at the -OH carbon, then the halogen gets the
        # lowest remaining locant. Cross-checked against PubChem.
        ("OC1CCCCC1Cl", "2-chlorocyclohexan-1-ol"),
        # A plain, unsubstituted ring bearing no -OH of its own, with the
        # -OH on a chain hanging off the ring instead: the chain (not the
        # ring) is the parent, and the ring is cited as a "cyclo..."
        # substituent prefix. Mononuclear (one-carbon) chain, so P-14.3.4.2(a)
        # omits the -OH locant same as plain 'methanol' -- cross-checked
        # against PubChem CID 7507 ("Cyclohexylmethanol").
        ("OCC1CCCCC1", "cyclohexylmethanol"),
        # Same shape, two-carbon chain. This falls into the same
        # already-documented ambiguous case as '2-chloroethanol' above (see
        # module docstring's P-14.3.4.2(a)/(b) note): PubChem's own
        # autogenerated name for this exact SMILES ('2-cyclohexylethanol')
        # omits the -OH locant, but this module deliberately always cites
        # it once the single-substituent omission precondition fails
        # (consistent with the halogen case already handled the same way),
        # so this is an accepted, reviewed result rather than a PubChem-
        # confirmed one.
        ("OCCC1CCCCC1", "2-cyclohexylethan-1-ol"),
        # Same ring-is-substituent shape, but the ring itself carries a
        # C=C double bond (P-31.1.3 + P-29.2): the free valence pins the
        # ring's numbering at position 1, so -- unlike the plain
        # 'cyclohexene' parent name -- a single double bond's locant is
        # never redundant and must always be cited, mirroring the Blue
        # Book's own 'triaz-1-en-1-yl' worked example of citing a '1'
        # locant that coincides with the fixed 'yl' attachment point
        # (P-68.3.1.4.1). PubChem's auto-generated name for this SMILES
        # drops that locant ('cyclohexen-1-ylmethanol'), a CAS-style
        # abbreviation rather than the 2013-recommendations PIN, so it's
        # not used as a cross-check here.
        ("OCC1=CCCCC1", "(cyclohex-1-en-1-yl)methanol"),
        # Same shape with the double bond elsewhere in the ring (numbering
        # direction chosen to give it the lower locant, 3 rather than 4).
        ("OCC1CC=CCC1", "(cyclohex-3-en-1-yl)methanol"),
        # Two ring double bonds: multiplying prefix + full locant set, same
        # as the plain-hydrocarbon diene case.
        ("OCC1=CC=CCC1", "(cyclohexa-1,3-dien-1-yl)methanol"),
        # A longer chain between the ring and the -OH still routes through
        # the same unsaturated-ring-substituent naming.
        ("OCCC1CC=CCC1", "2-(cyclohex-3-en-1-yl)ethan-1-ol"),
        # A single specified tetrahedral stereocenter (P-92): the Blue Book's own
        # worked example for this exact suffix, cross-checked against
        # PubChem CID 84682/444683 for the two enantiomers.
        ("C[C@@H](O)CC", "(2R)-butan-2-ol"),
        ("C[C@H](O)CC", "(2S)-butan-2-ol"),
        # A specified stereocenter combined with existing ene-suffix
        # support: the Blue Book's other own worked example for this
        # suffix, cross-checked against PubChem CID 6994331.
        ("C=C[C@H](O)CC", "(3R)-pent-1-en-3-ol"),
        # Two specified stereocenters (P-92/P-91.3): ascending-locant,
        # comma-separated citation in one parenthesized group -- both
        # diastereomers cross-checked against PubChem CID 12575191/11389370.
        ("C[C@H]([C@@H](C)Cl)O", "(2R,3R)-3-chlorobutan-2-ol"),
        ("C[C@H]([C@H](C)Cl)O", "(2R,3S)-3-chlorobutan-2-ol"),
        # A genuine stereocenter left *unspecified* in the input (no
        # `@`/`@@`) is not a new rejection case -- it's named exactly as
        # before (no stereodescriptor), matching both this project's prior
        # behavior and PubChem's own convention for a name that doesn't
        # specify configuration at all.
        ("CC(O)CC", "butan-2-ol"),
        # A plain, unsubstituted benzene ring on a chain hanging off it,
        # -OH on the chain itself (P-2/P-3 aromatic-ring-substituent
        # extension, mirroring PR #269/#270's carboxylic-acid/ketone
        # chains): the ring is cited as a "phenyl" substituent prefix.
        # Mononuclear chain, so P-14.3.4.2(a) omits the -OH locant, same as
        # the aliphatic 'cyclohexylmethanol' case above. Cross-checked
        # against PubChem CID 244 ("phenylmethanol").
        ("c1ccccc1CO", "phenylmethanol"),
        # Two-carbon chain: falls into the same always-cite-the-locant
        # case as '2-cyclohexylethan-1-ol' above once a substituent
        # prefix is present. PubChem's own name for this SMILES
        # ('2-phenylethanol', CID 6054) omits the locant; not used as a
        # cross-check here for the same reason as the cyclohexyl case.
        ("c1ccccc1CCO", "2-phenylethan-1-ol"),
        # -OH mid-chain rather than at the far terminus from the ring.
        ("c1ccccc1CC(O)C", "1-phenylpropan-2-ol"),
    ],
)
def test_alcohol_names(smiles, expected):
    assert smiles_to_iupac(smiles) == expected


def test_multiple_stereocenters_supported():
    # 3-methylpentan-2-ol, two specified stereocenters -- PubChem-verified
    # exactly for this SMILES ('(2S,3R)-3-methylpentan-2-ol', CID 6993006).
    assert smiles_to_iupac("C[C@H](O)[C@H](C)CC") == "(2S,3R)-3-methylpentan-2-ol"


def test_stereocenter_with_ez_double_bond_coexistence():
    # P-91.3: a specified tetrahedral
    # stereocenter and a specified C=C double-bond E/Z element are cited
    # together in one ascending-locant group. PubChem CID 6999919 confirms
    # the structure (ConnectivitySMILES "CC=CC(C)O"), though PubChem's own
    # auto-generated name groups by type ("(E,2S)-...") rather than by
    # ascending locant -- known unreliable for exact PIN citation order
    # (see also the thioic-acid tautomer-collapse case), so the expected
    # locant-ascending form here is the primary source's own rule, not
    # PubChem's.
    assert smiles_to_iupac("C[C@H](O)/C=C/C") == "(2S,3E)-pent-3-en-2-ol"


def test_ez_and_rs_coexistence_matches_bluebook_worked_example():
    # Exact reproduction of the Blue Book's own P-91.3 worked example,
    # "(2Z,5R,7E)-nona-2,7-dien-5-ol (PIN)" -- the strongest form of
    # verification available (primary source, not a derived/guessed case).
    assert smiles_to_iupac("C/C=C\\C[C@H](O)C/C=C/C") == "(2Z,5R,7E)-nona-2,7-dien-5-ol"


def test_partially_specified_stereocenters_raises():
    # one specified, one left unspecified -- an ambiguous mix, not the
    # same as "no stereo specified at all".
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("C[C@H](O)C(C)CC")


def test_specified_double_bond_with_unspecified_stereocenter_raises():
    # E/Z specified but the coexisting stereocenter (C2: CH3/OH/H/propenyl,
    # all different) is left unspecified -- same "ambiguous partial mix"
    # policy as test_partially_specified_stereocenters_raises, now also
    # covering a mix across the two different kinds of stereo element.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("CC(O)/C=C/C")


def test_ring_stereocenter_raises():
    # only one of the two ring stereocenters is specified (methyl carbon
    # left unmarked) -- a genuinely ambiguous partial specification, same
    # class of rejection as test_partially_specified_stereocenters_raises
    # above, not "ring stereocenters are unsupported" (see the two
    # positive ring tests below for the fully-specified case).
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("O[C@H]1CCCCC1C")


def test_ring_stereocenters_supported():
    # trans-2-methylcyclohexan-1-ol, both ring stereocenters specified --
    # PubChem CID 642632's own auto-generated name is
    # "trans-(1S,2S)-2-methylcyclohexan-1-ol"; the "trans-" is PubChem's
    # own redundant relative descriptor alongside R/S and is dropped here,
    # matching this project's existing acyclic convention of citing R/S
    # alone.
    assert smiles_to_iupac("O[C@H]1CCCC[C@@H]1C") == "(1S,2S)-2-methylcyclohexan-1-ol"


def test_ring_stereocenters_other_diastereomer_supported():
    # cis-2-methylcyclohexan-1-ol, the other diastereomer -- PubChem CID
    # 24006's own auto-generated name is "cis-(1R,2S)-2-methylcyclohexan-1-ol"
    # (again dropping the redundant "cis-").
    assert smiles_to_iupac("O[C@@H]1CCCC[C@@H]1C") == "(1R,2S)-2-methylcyclohexan-1-ol"


def test_ring_branch_stereocenter_supported():
    # 1-[(2S)-butan-2-yl]cyclohexan-1-ol: the ring's sole substituent (a
    # sec-butyl group) carries the only specified stereocenter, mirroring
    # `_aromatic.py`'s identical single-branch-stereocenter case (see
    # `_ring_branch_stereo_display`) -- PubChem PUG REST's own computed
    # IUPACName for this exact SMILES confirms the bracketed descriptor
    # embeds into the substituent name rather than citing a ring locant.
    assert smiles_to_iupac("OC1(CCCCC1)[C@@H](C)CC") == "1-[(2S)-butan-2-yl]cyclohexan-1-ol"


def test_ring_branch_two_stereocenters_raises():
    # more than one specified stereocenter on the branch is outside this
    # narrow slice's scope (mirrors `_aromatic.py`'s identical limit),
    # still falling through to the general "stereocenter on a substituent
    # branch" rejection rather than being (mis)handled.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OC1(CCCCC1)[C@@H]([C@H](C)Cl)CC")


def test_polycyclic_ring_stereocenter_raises():
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("O[C@H]1CCCC2CCCC12")


def test_three_stereocenters_supported():
    # Three specified stereocenters on one chain: not independently found
    # on PubChem, but the prefix-joining logic this exercises (sorting by
    # locant, comma-joining N pairs) is a simple, directly-inspectable
    # generalization of the already-verified two-stereocenter case above,
    # and CIP computation itself is fully delegated to RDKit, not
    # reimplemented -- a reviewed, not independently confirmed, result.
    assert smiles_to_iupac("CC[C@H](C)[C@@H](Cl)[C@H](C)O") == "(2S,3R,4S)-3-chloro-4-methylhexan-2-ol"


def test_pseudoasymmetric_stereocenter_raises():
    # pentane-2,3,4-triol built with the outer two centers as mirror
    # images of each other: RDKit's rdCIPLabeler assigns the middle center
    # a lowercase 'r' (pseudoasymmetric), out of scope here (see
    # this project
    # doesn't attempt to verify pseudoasymmetric CIP assignment itself.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("C[C@@H](O)[C@H](O)[C@@H](O)C")




def test_ring_with_own_hydroxyl_and_chain_hydroxyl():
    # the ring bears exactly one -OH *and* a single unbranched chain
    # substituent also bears exactly one -OH: a genuine P-44.1.2.2 tie
    # (both candidate parents capture exactly one -OH), which P-44.1.2.2
    # always resolves in the ring's favor. Cross-checked against PubChem
    # PUG REST: CID 5175258 (OC1CCCCC1CO) ->
    # "2-(hydroxymethyl)cyclohexan-1-ol".
    assert smiles_to_iupac("OC1CCCCC1CO") == "2-(hydroxymethyl)cyclohexan-1-ol"


def test_tetrasubstituted_ring_atom_with_own_hydroxyl_and_chain_hydroxyl():
    # the same ring carbon carries both the ring's own -OH and the
    # OH-bearing chain branch. Cross-checked against PubChem PUG REST:
    # CID 251259 (OC1(CO)CCCCC1) -> "1-(hydroxymethyl)cyclohexan-1-ol".
    assert smiles_to_iupac("OC1(CO)CCCCC1") == "1-(hydroxymethyl)cyclohexan-1-ol"


def test_ring_hydroxyl_count_exceeds_chain():
    # the ring has two -OH's, the chain has one: P-44.1.1's principal-group
    # count settles it outright in the ring's favor (no tie needed).
    # Cross-checked against PubChem PUG REST: CID 18944701
    # (OC1C(O)CC(CO)CC1) -> "4-(hydroxymethyl)cyclohexane-1,2-diol".
    assert smiles_to_iupac("OC1C(O)CC(CO)CC1") == "4-(hydroxymethyl)cyclohexane-1,2-diol"


def test_ring_hydroxyl_count_exceeds_chain_by_two():
    # CID 22311515 (OC1C(O)C(O)C(CO)CC1) ->
    # "4-(hydroxymethyl)cyclohexane-1,2,3-triol".
    assert smiles_to_iupac("OC1C(O)C(O)C(CO)CC1") == "4-(hydroxymethyl)cyclohexane-1,2,3-triol"


def test_equal_hydroxyl_counts_above_one_each():
    # ring and chain both have two -OH's: still a tie, resolved in the
    # ring's favor the same way as the one-each tie above. CID 22670583
    # (OC1C(O)CC(C(O)CO)CC1) -> "4-(1,2-dihydroxyethyl)cyclohexane-1,2-diol".
    assert smiles_to_iupac("OC1C(O)CC(C(O)CO)CC1") == "4-(1,2-dihydroxyethyl)cyclohexane-1,2-diol"


def test_chain_hydroxyl_count_exceeds_ring_now_supported():
    # the chain has more -OH's than the ring (two vs. one): the chain is
    # now the senior parent (P-44.1.1) and the ring, with its own single
    # -OH, is cited as a substituent.
    # PubChem-verified exactly (CID 130142401).
    assert smiles_to_iupac("OC1CCCCC1C(O)CO") == "1-(2-hydroxycyclohexyl)ethane-1,2-diol"


def test_chain_hydroxyl_count_exceeds_ring_with_no_ring_hydroxyl_chain():
    # the ring's own -OH, chain has none besides -- exercises
    # `_ring_substituent_with_hydroxyl` via the plain
    # `_name_ring_substituent_chain_alcohol` path (ring bears an -OH but
    # the chain substituent doesn't compete for the suffix at all, so the
    # ring is simply the sole -OH-bearing parent, unaffected by this
    # task's new ring-vs-chain wiring).
    assert smiles_to_iupac("OC1CCC(CC)CC1") == "4-ethylcyclohexan-1-ol"


def test_ring_with_two_hydroxyls_outcompeted_by_chain():
    # The ring has two of its own -OH's, but the chain has three, so the
    # chain is the senior parent and the ring is cited as a
    # "(dihydroxycyclohexyl)" substituent. No PubChem-listed compound was found for this exact
    # structure, so this is a reviewed (eyeballed), not independently
    # verified, result -- a generalization of the already-verified
    # single-ring-hydroxyl mechanism (see `_substituents.py`'s
    # `_ring_substituent_with_hydroxyls` docstring). Ring locants 3,4 are
    # hand-verified as the lower of the two possible directions (the
    # alternative gives 4,5).
    assert smiles_to_iupac("OC1C(O)CCC(C(O)C(O)CO)C1") == "1-(3,4-dihydroxycyclohexyl)propane-1,2,3-triol"


def test_phenyl_substituted_benzene_ring_ortho_methyl():
    # A ring methyl substituent is now supported (see
    # tasks/aromatic-ring-methyl-substituent.md) -- PubChem PUG
    # REST-verified "2-(2-methylphenyl)ethanol".
    assert smiles_to_iupac("Cc1ccccc1CCO") == "2-(2-methylphenyl)ethan-1-ol"


def test_phenyl_chain_with_second_hydroxyl_raises():
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OCc1ccccc1CO")


def test_phenyl_chain_unsaturation_raises():
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("C=Cc1ccccc1CO")


def test_phenyl_chain_ring_halogen():
    # The ring's other atoms may each carry a single halogen alongside the
    # -OH chain attachment (PubChem CID 18825 IUPACName "1-(4-chlorophenyl)
    # ethanol").
    assert smiles_to_iupac("OC(C)c1ccc(Cl)cc1") == "1-(4-chlorophenyl)ethan-1-ol"


def test_phenyl_chain_ring_dihalogen():
    # PubChem CID 244558 "2-(3,4-dichlorophenyl)ethanol".
    assert smiles_to_iupac("Clc1ccc(cc1Cl)CCO") == "2-(3,4-dichlorophenyl)ethan-1-ol"


def test_phenyl_chain_ring_methyl():
    # PubChem PUG REST-verified "2-(4-methylphenyl)ethanol" -- same
    # non-halogen-specific mechanism as the halogen cases above, now fed
    # a plain methyl ring substituent instead.
    assert smiles_to_iupac("CC1=CC=C(CCO)C=C1") == "2-(4-methylphenyl)ethan-1-ol"


def test_phenyl_chain_ring_ethyl():
    # PubChem PUG REST IUPACName match: any plain, fully saturated
    # acyclic alkyl ring substituent (not just methyl) is now supported,
    # reusing `name_branch` itself via `plain_alkyl_ring_substituents`.
    assert smiles_to_iupac("CCc1ccc(cc1)CO") == "(4-ethylphenyl)methanol"


def test_substituted_ring_with_chain_hydroxyl_raises():
    # the ring itself carries an extra substituent (not just the OH-bearing
    # chain) -- out of this module's minimal scope.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OCC1CCCCC1C")


def test_branched_chain_hydroxyl_on_ring():
    # A branch on the chain hanging off the ring is absorbed into the
    # parent chain (`longest_branched_chain_through`, P-44.3.2), same
    # principle as `_carboxylic_acid.py`'s ibuprofen case. PubChem PUG
    # REST-verified "2-cyclohexylpropan-1-ol".
    assert smiles_to_iupac("OCC(C)C1CCCCC1") == "2-cyclohexylpropan-1-ol"


def test_carboxylic_acid_not_misread_as_alcohol():
    # -C(=O)-OH: a carboxylic acid is a more senior characteristic group
    # (Table 3.3) than a plain alcohol; must not be misread as one (it's
    # routed to the dedicated carboxylic-acid module instead, see
    # test_carboxylic_acid.py).
    assert smiles_to_iupac("CC(=O)O") == "ethanoic acid"


def test_ketone_hetero_mix_dispatches_to_ketone_module():
    # A structure with both -OH and a ketone C=O: 'one' outranks 'ol' in
    # Table 3.3, so the ketone module (see test_ketone.py) names it with
    # 'hydroxy' as a substituent prefix instead of this module's own suffix.
    assert smiles_to_iupac("OCC(=O)C") == "1-hydroxypropan-2-one"


def test_aldehyde_alcohol_mix_dispatches_to_aldehyde_module():
    # A structure with both -OH and an aldehyde-shaped carbonyl: 'al'
    # outranks 'ol' in Table 3.3, so the aldehyde module (see
    # test_aldehyde.py) names it with 'hydroxy' as a substituent prefix
    # instead of this module's own suffix.
    assert smiles_to_iupac("OCC=O") == "2-hydroxyethanal"


def test_phenol():
    # -OH attached directly to a benzene ring carbon (P-63.1.1). PubChem
    # PUG REST: "phenol"/"4-methylphenol"/"2-chlorophenol" -- the retained
    # name 'phenol' stands for the whole ring+OH system (like 'benzoic
    # acid'/'benzenesulfonic acid'), so the OH's own ring locant is never
    # cited, only other substituents'.
    assert smiles_to_iupac("Oc1ccccc1") == "phenol"
    assert smiles_to_iupac("Oc1ccc(C)cc1") == "4-methylphenol"
    assert smiles_to_iupac("Oc1ccccc1Cl") == "2-chlorophenol"


def test_phenol_multiple_hydroxyls_raises():
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("Oc1ccccc1O")


def test_bicyclic_alcohol_raises():
    # Same skeleton as test_halogens.py's 'ClC1CC2CCC1CC2' ->
    # '2-chlorobicyclo[2.2.2]octane', with the halogen swapped for -OH: a
    # real, nameable compound ('bicyclo[2.2.2]octan-2-ol', confirmed via
    # PubChem), but von Baeyer polycyclic alcohols are explicitly deferred.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OC1CC2CCC1CC2")


def test_ethoxyethanol():
    # A simple alkoxy ether coexisting with a hydroxyl on an acyclic
    # chain (P-29.3.3) is supported: PubChem's own name is
    # '2-ethoxyethanol' (CID 8076), but this falls into the same
    # documented two-carbon-chain locant-citation edge case as
    # '2-cyclohexylethan-1-ol' above -- this module always cites the -OH
    # locant once a substituent is present, an accepted, reviewed result
    # rather than a PubChem-confirmed one for this specific chain length.
    assert smiles_to_iupac("OCCOCC") == "2-ethoxyethan-1-ol"


def test_methoxypropanol():
    # No two-carbon-chain ambiguity here, so this matches PubChem
    # directly. CID 8109.
    assert smiles_to_iupac("OCCCOCC") == "3-ethoxypropan-1-ol"


def test_two_alkoxy_ethers():
    # Two simple alkoxy ethers each get their own substituent prefix, the
    # same generic mechanism as any other multi-substituent case. PubChem
    # CID 12486323.
    assert smiles_to_iupac("OCC(OC)COC") == "2,3-dimethoxypropan-1-ol"


def test_branched_ether_raises():
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OCCOC(C)C")


def test_ether_on_ring_raises():
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OC1CCCCC1OC")


def test_enol_raises():
    # -OH on a carbon that is also part of a C=C bond: deliberately
    # narrowed out of scope (see module docstring).
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OC=CC")


def test_unsaturated_ring_alcohol_with_substituent_raises():
    # A substituent alongside both a ring double bond and a ring hydroxyl
    # needs more careful numbering-priority verification than this first
    # pass covers.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OC1CCCC=C1C")


def test_unsaturated_ring_alcohol_triple_bond_raises():
    # A ring triple bond (cycloalkyne) alongside a hydroxyl is out of
    # scope for this first pass -- only a ring double bond is supported.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("OC1CCCC#C1")


def test_amine_hetero_mix_dispatches_to_alcohol_amine():
    # A structure with both -OH and a primary amine is now handled by the
    # separate `_alcohol_amine.py` seniority-coexistence module (P-41,
    # '-ol' outranks 'amine') rather than being rejected here -- see
    # test_alcohol_amine.py for that module's own coverage. PubChem CID
    # 700's own IUPACName is '2-aminoethanol' (the retained 'ethanol' stem
    # kept even when substituted); this module already diverges from that
    # convention for a substituted ethanol (e.g. '2-ethoxyethan-1-ol'
    # above), so '_alcohol_amine.py' follows that same pre-existing
    # convention instead.
    assert smiles_to_iupac("OCCN") == "2-aminoethan-1-ol"


def test_branch_point_prefers_halogen_bearing_arm_over_plain_alkyl_arm():
    # Found via real-data testing: `_common.py`'s `longest_branched_chain_
    # through` (shared by ~20 suffix modules) resolved a tie between two
    # equal-length one-carbon arms off the alcohol carbon (a plain methyl
    # vs a halogen-bearing carbon) arbitrarily, by BFS/adjacency insertion
    # order, instead of applying the same "more substituents cited as
    # prefixes" tie-break its sibling `longest_branched_chain` already
    # uses (P-44.3.2) -- both examples below are PubChem's own PINs.
    assert (
        smiles_to_iupac("CCCCc1ccc(C(O)(CCC)C(C)C(F)F)cc1")
        == "3-(4-butylphenyl)-1,1-difluoro-2-methylhexan-3-ol"
    )
    assert (
        smiles_to_iupac("CC(O)(Cc1cccc(F)c1)C(F)(F)Br")
        == "1-bromo-1,1-difluoro-3-(3-fluorophenyl)-2-methylpropan-2-ol"
    )
