import pytest

from smiles_to_iupac import smiles_to_iupac
from smiles_to_iupac._common import UnsupportedStructure


@pytest.mark.parametrize(
    "smiles,expected",
    [
        # cross-checked against PubChem PUG REST IUPACName:
        # CID 68973 (CP), CID 69607 (CPC), CID 136382 (CCP),
        # CID 68983 (CP(C)C), CID 27365 (CCP(CC)CC), CID 20221924 (CCPC).
        ("CP", "methylphosphane"),
        ("CPC", "dimethylphosphane"),
        ("CCP", "ethylphosphane"),
        ("CP(C)C", "trimethylphosphane"),
        ("CCP(CC)CC", "triethylphosphane"),
        ("CCPC", "ethyl(methyl)phosphane"),
        # three different substituents: PubChem's own autogenerated name
        # ("ethyl-methyl-propylphosphane") does not follow the Blue Book's
        # own published errata rule (P-16.5.1.3.1, parenthesize every
        # substituent after the alphabetically first when locants are
        # omitted) -- applying that rule directly instead, cross-checked
        # against the analogous silane errata example
        # "butyl(ethyl)(methyl)(propyl)silane".
        ("CCP(C)CCC", "ethyl(methyl)(propyl)phosphane"),
    ],
)
def test_smiles_to_iupac_simple_phosphane(smiles, expected):
    assert smiles_to_iupac(smiles) == expected


def test_phosphane_chain_raises():
    # diphosphane (P-P bond): two phosphorus atoms, a separate "chain"
    # nomenclature problem this module doesn't handle.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("PP")


def test_branched_substituent_raises():
    # isopropylphosphane: a branched substituent is out of scope.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("CC(C)P")


def test_unsaturated_substituent_raises():
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("C=CP")


def test_mixed_multiplied_and_different_substituent_raises():
    # two methyls plus one ethyl: the multiplying-prefix/parentheses
    # interaction for this case isn't confirmed, deferred.
    with pytest.raises(UnsupportedStructure):
        smiles_to_iupac("CCP(C)C")
