"""Naming of simple boranes (BH3 bearing 1-3 unbranched, saturated alkyl
substituents), per the IUPAC 2013 Recommendations ("the Blue Book"):

- P-68 (Chapter P-6, https://iupac.qmul.ac.uk/BlueBook/PDF/P6.pdf): like
  phosphane (`_phosphane.py`), a borane's parent hydride is the boron atom
  itself (BH3, "borane"); alkyl groups are cited as substituent prefixes in
  a purely substitutive name, e.g. "methylborane". This module is
  structurally identical to `_phosphane.py` (same validation shape, same
  P-14.3.4.2(a) locant omission, same P-16.5.1.3.1 parenthesization
  errata) with boron in place of phosphorus -- confirmed via PubChem PUG
  REST (2026-08-25) for exactly the case set `_phosphane.py` already
  supports, mirroring each of that module's own worked examples:
  CID 6331 (`B`) -> "borane", CID 5326078 (`CB`) -> "methylborane",
  CID 15879358 (`CBC`) -> "dimethylborane", CID 68979 (`CB(C)C`) ->
  "trimethylborane", CID 7357 (`CCB(CC)CC`) -> "triethylborane",
  CID 143352201 (`CCBC`, ethyl + methyl) -> "ethyl(methyl)borane",
  CID 517955 (`CCB(C)C`, ethyl x1 + methyl x2) -> "ethyl(dimethyl)borane",
  CID 543198 (`CCB(CC)C`, ethyl x2 + methyl x1) -> "diethyl(methyl)borane".
- P-14.3.4.2(a): boron is the sole skeletal atom of the parent hydride, so
  every substituent's locant is always '1' and is never cited.
- P-16.5.1.3.1 (per the Blue Book's own published errata,
  https://iupac.qmul.ac.uk/bibliog/BBerrors.html): when two or more
  *different* substituent prefixes are cited without locants on a
  mononuclear parent, the first (alphabetically) is never parenthesized,
  but every subsequent one is -- see `_phosphane.py`'s docstring for the
  full derivation (identical here). For three different substituents,
  PubChem's own autogenerated name doesn't follow this rule (the same
  known engine gap noted in `_phosphane.py`), so the errata's rule text is
  applied directly instead.
- Multiple *identical* substituents use the ordinary multiplying prefix
  (di-, tri-) with no parentheses; a multiply-cited substituent mixed with
  a different one combines both rules, exactly as in `_phosphane.py`.

- A halogen (F/Cl/Br/I) bonded directly to boron is just another
  substituent prefix that already fits the P-16.5.1.3.1 parenthesization
  rule above (no new mechanism needed) -- confirmed via PubChem PUG REST:
  CID 140714 (`ClB`) -> "chloroborane", CID 137221 (`ClB(C)C`) ->
  "chloro(dimethyl)borane".

- A branched substituent is supported (e.g. 'propan-2-ylborane', CID
  101871698), built with `name_branch`, following exactly the same
  compound/multiplying parenthesization rules as `_phosphane.py` -- see
  that module's docstring and `format_mononuclear_prefixes`'s own
  docstring for the full derivation.

Explicitly out of scope (raise `UnsupportedStructure`):
- Any atom other than boron, carbon, hydrogen, and a halogen bonded
  directly to boron (no B=O, no halogen-substituted alkyl chain, no other
  heteroatom in a substituent chain).
- More than one boron atom (borane chains, e.g. diborane -- a separate,
  genuinely different structure/nomenclature problem, not a simple
  extension of this substitutive-naming scope).
- An unsaturated substituent, an aromatic substituent (phenylborane,
  etc.), or any ring anywhere in the molecule.
- Charged or isotopically modified atoms.
- A structure that also contains phosphorus (or any other heteroatom):
  rejected by the "heteroatoms other than boron itself" check below, same
  as `_phosphane.py` rejects a structure that also contains boron.
"""

from rdkit import Chem

from ._common import (
    HALOGEN_PREFIXES,
    UnsupportedStructure,
    adjacency,
    non_single_bonds,
)
from ._substituents import format_mononuclear_prefixes, name_branch


def has_simple_borane_shape(mol) -> bool:
    return any(atom.GetAtomicNum() == 5 for atom in mol.GetAtoms())


def _validate_and_collect_substituents(mol):
    boron_atoms = [atom for atom in mol.GetAtoms() if atom.GetAtomicNum() == 5]
    if len(boron_atoms) != 1:
        raise UnsupportedStructure(
            "more than one boron atom is not supported yet (see P-68, "
            "borane chain nomenclature is a separate problem)"
        )
    (boron,) = boron_atoms
    if boron.GetFormalCharge() != 0 or boron.GetIsotope() != 0:
        raise UnsupportedStructure("charged or isotopically modified atoms are not supported yet")
    if boron.GetDegree() > 3:
        raise UnsupportedStructure("a boron atom with more than three substituents is not a borane")

    for atom in mol.GetAtoms():
        is_halogen = atom.GetAtomicNum() in HALOGEN_PREFIXES
        if atom.GetAtomicNum() not in (5, 6) and not is_halogen:
            raise UnsupportedStructure(
                "heteroatoms other than the borane boron itself are not "
                "supported yet (see P-68)"
            )
        if is_halogen and (
            atom.GetDegree() != 1 or atom.GetNeighbors()[0].GetIdx() != boron.GetIdx()
        ):
            raise UnsupportedStructure(
                "a halogen-substituted alkyl chain is out of scope for this "
                "module -- only a halogen bonded directly to boron is "
                "supported so far"
            )
        if atom.GetFormalCharge() != 0 or atom.GetIsotope() != 0:
            raise UnsupportedStructure("charged or isotopically modified atoms are not supported yet")
        if atom.GetAtomicNum() == 6 and atom.GetIsAromatic():
            raise UnsupportedStructure("an aromatic substituent (e.g. phenylborane) is out of scope")
    if mol.GetRingInfo().NumRings() != 0:
        raise UnsupportedStructure("a ring anywhere in the molecule is out of scope for this module")
    if non_single_bonds(mol):
        raise UnsupportedStructure(
            "an unsaturated substituent is out of scope for this module (see P-68)"
        )
    if len(Chem.GetMolFrags(mol)) > 1:
        raise UnsupportedStructure("multi-fragment structures are not supported yet")

    graph = adjacency(mol)
    substituent_names = []
    for root in graph[boron.GetIdx()]:
        root_atomic_num = mol.GetAtomWithIdx(root).GetAtomicNum()
        if root_atomic_num in HALOGEN_PREFIXES:
            substituent_names.append((HALOGEN_PREFIXES[root_atomic_num], False))
            continue
        substituent_names.append(name_branch(graph, root, boron.GetIdx(), {}))
    return substituent_names


def name_simple_borane(mol) -> str:
    substituent_names = _validate_and_collect_substituents(mol)
    if not substituent_names:
        return "borane"
    return format_mononuclear_prefixes(substituent_names) + "borane"
