"""Naming of simple boranes (BH3 bearing 1-3 unbranched, saturated alkyl
and/or plain phenyl substituents), per the IUPAC 2013 Recommendations
("the Blue Book"):

- P-68 (Chapter P-6, https://iupac.qmul.ac.uk/BlueBook/PDF/P6.pdf): like
  phosphane (`_phosphane.py`), a borane's parent hydride is the boron atom
  itself (BH3, "borane"); alkyl groups are cited as substituent prefixes in
  a purely substitutive name, e.g. "methylborane". This module is
  structurally identical to `_phosphane.py` (same validation shape, same
  P-14.3.4.2(a) locant omission, same P-16.5.1.3.1 parenthesization
  errata) with boron in place of phosphorus -- confirmed via PubChem PUG
  REST (2026-08-25) for exactly the case set `_phosphane.py` already
  supports, mirroring each of that module's own worked examples:
  CID 6331 (`B`) -> "borane", CID 5326078 (`CB`) -> "methylborane",
  CID 15879358 (`CBC`) -> "dimethylborane", CID 68979 (`CB(C)C`) ->
  "trimethylborane", CID 7357 (`CCB(CC)CC`) -> "triethylborane",
  CID 143352201 (`CCBC`, ethyl + methyl) -> "ethyl(methyl)borane".
  For a multiplied substituent mixed with a different one, this module's
  own output (via the shared `format_mononuclear_prefixes` helper) is
  "ethyldi(methyl)borane" (CID 517955's structure, ethyl x1 + methyl x2)
  and "diethyl(methyl)borane" (CID 543198's structure, ethyl x2 + methyl
  x1) -- the multiplying prefix always sits *outside* the parentheses,
  confirmed via the Blue Book's own "chlorodi(methyl)borane (PIN)"
  worked example (`tmp/bluebook/P6.txt`), not PubChem's own raw
  "ethyl(dimethyl)borane" for the first case (see `_phosphane.py`'s
  docstring for the full derivation of this correction).
- P-14.3.4.2(a): boron is the sole skeletal atom of the parent hydride, so
  every substituent's locant is always '1' and is never cited.
- P-16.5.1.3.1 (per the Blue Book's own published errata,
  https://iupac.qmul.ac.uk/bibliog/BBerrors.html): when two or more
  *different* substituent prefixes are cited without locants on a
  mononuclear parent, the first (alphabetically) is never parenthesized,
  but every subsequent one is -- see `_phosphane.py`'s docstring for the
  full derivation (identical here). For three different substituents,
  PubChem's own autogenerated name doesn't follow this rule (the same
  known engine gap noted in `_phosphane.py`), so the errata's rule text is
  applied directly instead.
- Multiple *identical* substituents use the ordinary multiplying prefix
  (di-, tri-) with no parentheses; a multiply-cited substituent mixed with
  a different one combines both rules, exactly as in `_phosphane.py`.

- A halogen (F/Cl/Br/I) bonded directly to boron is just another
  substituent prefix that already fits the P-16.5.1.3.1 parenthesization
  rule above (no new mechanism needed) -- confirmed via PubChem PUG REST
  for structure only: CID 140714 (`ClB`) -> "chloroborane"; CID 137221's
  structure (`ClB(C)C`) is named "chlorodi(methyl)borane" here, matching
  the Blue Book's own "chlorodi(methyl)borane (PIN)" worked example
  directly (not PubChem's own raw "chloro(dimethyl)borane").

- A branched substituent is supported (e.g. 'propan-2-ylborane', CID
  101871698), built with `name_branch`, following exactly the same
  compound/multiplying parenthesization rules as `_phosphane.py` -- see
  that module's docstring and `format_mononuclear_prefixes`'s own
  docstring for the full derivation.
- A plain, unsubstituted benzene ring bonded directly to boron is cited
  as a 'phenyl' substituent, mixed freely with alkyl/halogen substituents
  -- confirmed via PubChem PUG REST: `c1ccccc1B` -> "phenylborane" (CID
  101697465), `c1ccccc1B(c1ccccc1)c1ccccc1` -> "triphenylborane" (CID
  70400). Unlike `_phosphanone.py`'s identical extension (P=O, PR #395),
  boron's normal valence is exactly 3, so three phenyl substituents never
  trigger a lambda-convention label -- this mirrors the plain
  'trimethylborane' shape exactly, with no P-14.1 complication at all.
  Detection reuses the same `_plain_phenyl_substituent_atoms` pattern
  (`is_plain_benzene_ring` + `ring_chain_attachment`) adapted for boron's
  own direct-neighbor substituent roots.

Explicitly out of scope (raise `UnsupportedStructure`):
- Any atom other than boron, carbon, hydrogen, and a halogen bonded
  directly to boron (no B=O, no halogen-substituted alkyl chain, no other
  heteroatom in a substituent chain).
- More than one boron atom (borane chains, e.g. diborane -- a separate,
  genuinely different structure/nomenclature problem, not a simple
  extension of this substitutive-naming scope).
- An unsaturated substituent, an aromatic substituent other than a plain,
  unsubstituted phenyl (a substituted or heteroaromatic ring, e.g.), or a
  ring other than a plain phenyl substituent directly on boron.
- Charged or isotopically modified atoms.
- A structure that also contains phosphorus (or any other heteroatom):
  rejected by the "heteroatoms other than boron itself" check below, same
  as `_phosphane.py` rejects a structure that also contains boron.
"""

from rdkit import Chem

from ._common import (
    HALOGEN_PREFIXES,
    UnsupportedStructure,
    adjacency,
    is_plain_benzene_ring,
    non_single_bonds,
    ring_chain_attachment,
)
from ._substituents import format_mononuclear_prefixes, name_branch


def has_simple_borane_shape(mol) -> bool:
    return any(atom.GetAtomicNum() == 5 for atom in mol.GetAtoms())


def _plain_phenyl_substituent_atoms(mol, graph, roots):
    """Union of ring atoms for every plain, unsubstituted benzene ring in
    `mol` that hangs directly off one of `roots` (the borane boron's own
    substituent neighbors) with no other exocyclic attachment -- i.e. a
    lone 'phenyl' substituent directly on boron. Mirrors
    `_phosphanone.py`'s identical helper (itself mirroring
    `_carbamate.py`'s), adapted for boron in place of phosphorus."""
    atoms = set()
    for ring in mol.GetRingInfo().AtomRings():
        ring_atoms = set(ring)
        if not is_plain_benzene_ring(mol, ring_atoms):
            continue
        attachment = ring_chain_attachment(graph, ring_atoms, set())
        if attachment is None:
            continue
        ring_atom, _ = attachment
        if ring_atom in roots:
            atoms |= ring_atoms
    return atoms


def _validate_and_collect_substituents(mol):
    boron_atoms = [atom for atom in mol.GetAtoms() if atom.GetAtomicNum() == 5]
    if len(boron_atoms) != 1:
        raise UnsupportedStructure(
            "more than one boron atom is not supported yet (see P-68, "
            "borane chain nomenclature is a separate problem)"
        )
    (boron,) = boron_atoms
    if boron.GetFormalCharge() != 0 or boron.GetIsotope() != 0:
        raise UnsupportedStructure("charged or isotopically modified atoms are not supported yet")
    if boron.GetDegree() > 3:
        raise UnsupportedStructure("a boron atom with more than three substituents is not a borane")

    graph = adjacency(mol)
    roots = set(graph[boron.GetIdx()])
    phenyl_atoms = _plain_phenyl_substituent_atoms(mol, graph, roots)

    for atom in mol.GetAtoms():
        is_halogen = atom.GetAtomicNum() in HALOGEN_PREFIXES
        if atom.GetAtomicNum() not in (5, 6) and not is_halogen:
            raise UnsupportedStructure(
                "heteroatoms other than the borane boron itself are not "
                "supported yet (see P-68)"
            )
        if is_halogen and (
            atom.GetDegree() != 1 or atom.GetNeighbors()[0].GetIdx() != boron.GetIdx()
        ):
            raise UnsupportedStructure(
                "a halogen-substituted alkyl chain is out of scope for this "
                "module -- only a halogen bonded directly to boron is "
                "supported so far"
            )
        if atom.GetFormalCharge() != 0 or atom.GetIsotope() != 0:
            raise UnsupportedStructure("charged or isotopically modified atoms are not supported yet")
        if atom.GetAtomicNum() == 6 and atom.GetIsAromatic() and atom.GetIdx() not in phenyl_atoms:
            raise UnsupportedStructure(
                "an aromatic substituent other than a plain, unsubstituted "
                "phenyl group is out of scope for this module"
            )
    all_ring_atoms = {a for ring in mol.GetRingInfo().AtomRings() for a in ring}
    if all_ring_atoms - phenyl_atoms:
        raise UnsupportedStructure(
            "a ring other than a plain phenyl substituent directly on "
            "boron is out of scope for this module"
        )
    non_ring_unsaturation = [
        b for b in non_single_bonds(mol) if b[0] not in phenyl_atoms and b[1] not in phenyl_atoms
    ]
    if non_ring_unsaturation:
        raise UnsupportedStructure(
            "an unsaturated substituent is out of scope for this module "
            "(see P-68)"
        )
    if len(Chem.GetMolFrags(mol)) > 1:
        raise UnsupportedStructure("multi-fragment structures are not supported yet")

    substituent_names = []
    for root in roots:
        if root in phenyl_atoms:
            substituent_names.append(("phenyl", False))
            continue
        root_atomic_num = mol.GetAtomWithIdx(root).GetAtomicNum()
        if root_atomic_num in HALOGEN_PREFIXES:
            substituent_names.append((HALOGEN_PREFIXES[root_atomic_num], False))
            continue
        substituent_names.append(name_branch(graph, root, boron.GetIdx(), {}))
    return substituent_names


def name_simple_borane(mol) -> str:
    substituent_names = _validate_and_collect_substituents(mol)
    if not substituent_names:
        return "borane"
    return format_mononuclear_prefixes(substituent_names) + "borane"
