"""Naming of simple phosphanes (PH3 bearing 1-3 unbranched, saturated alkyl
substituents), per the IUPAC 2013 Recommendations ("the Blue Book"):

- P-68 (Chapter P-6, https://iupac.qmul.ac.uk/BlueBook/PDF/P6.pdf):
  unlike amines (`_amine.py`, where a carbon chain is the parent hydride
  and -NH2 is cited as a suffix, e.g. "ethanamine"), a phosphane's parent
  hydride is the phosphorus atom itself (PH3, "phosphane"); alkyl groups
  are cited as substituent prefixes in a purely substitutive name, e.g.
  "methylphosphane" (not an amine-style "methanophosphine"). Confirmed via
  PubChem PUG REST: CID 68973 (`CP`) -> "methylphosphane", CID 69607
  (`CPC`) -> "dimethylphosphane", CID 136382 (`CCP`) -> "ethylphosphane",
  CID 68983 (`CP(C)C`) -> "trimethylphosphane", CID 27365
  (`CCP(CC)CC`) -> "triethylphosphane".
- P-14.3.4.2(a): phosphorus is the sole skeletal atom of the parent
  hydride, so every substituent's locant is always '1' and is never cited
  -- mirroring `_amine.py`'s/`_silane_chain.py`'s own mononuclear-parent
  locant omission, reused here via `format_substituent_prefixes`'s
  `omit_locants=True` mode.
- P-16.5.1.3.1 (per the Blue Book's own published errata,
  https://iupac.qmul.ac.uk/bibliog/BBerrors.html, correcting the original
  text's "butyl(ethyl)methyl(propyl)silane" to
  "butyl(ethyl)(methyl)(propyl)silane"): when two or more *different*
  substituent prefixes are cited without locants on a mononuclear parent,
  the first (alphabetically) is never parenthesized, but every subsequent
  one is -- even a plain simple substituent that would otherwise never be
  parenthesized (`format_substituent_prefixes` in `_substituents.py` only
  parenthesizes a "compound"/nested substituent, so that shared helper
  doesn't implement this locant-omission-specific rule; this module has
  its own formatter instead). Confirmed via PubChem for the two-different-
  substituent case: CID 20221924 (`CCPC`) -> "ethyl(methyl)phosphane", not
  "ethylmethylphosphane". For three different substituents, PubChem's own
  autogenerated name (`CCP(C)CCC` -> "ethyl-methyl-propylphosphane") does
  NOT follow this rule (a known gap in its naming engine, not usable as a
  cross-check here) -- the errata's rule text is applied directly instead,
  giving "ethyl(methyl)(propyl)phosphane".
- Multiple *identical* substituents use the ordinary multiplying prefix
  (di-, tri-) with no parentheses at all (P-16.5.1.3.1 doesn't apply --
  there's only one distinct substituent name to cite), e.g.
  "dimethylphosphane", "trimethylphosphane".

Explicitly out of scope (raise `UnsupportedStructure`):
- Any atom other than phosphorus, carbon, and hydrogen (no P=O, no
  halogen-substituted alkyl, no other heteroatom in a substituent chain).
- More than one phosphorus atom (phosphane chains, e.g. diphosphane --
  `_silane_chain.py`-style "chain" nomenclature is a separate problem).
- A branched or unsaturated substituent, an aromatic substituent
  (phenylphosphane, etc.), or any ring anywhere in the molecule.
- A mix of a multiply-cited substituent with a different one (e.g. two
  methyls plus one ethyl) -- the multiplying-prefix-and-parentheses
  interaction for that case isn't confirmed yet; deferred.
- Charged or isotopically modified atoms.
"""

from rdkit import Chem

from ._common import UnsupportedStructure, adjacency, linear_branch, non_single_bonds
from ._numerals import alkyl_name, multiplying_prefix
from ._substituents import alpha_sort_key


def has_simple_phosphane_shape(mol) -> bool:
    return any(atom.GetAtomicNum() == 15 for atom in mol.GetAtoms())


def _validate_and_collect_substituents(mol):
    phosphorus_atoms = [atom for atom in mol.GetAtoms() if atom.GetAtomicNum() == 15]
    if len(phosphorus_atoms) != 1:
        raise UnsupportedStructure(
            "more than one phosphorus atom is not supported yet (see P-68, "
            "phosphane chain nomenclature is a separate problem)"
        )
    (phosphorus,) = phosphorus_atoms
    if phosphorus.GetFormalCharge() != 0 or phosphorus.GetIsotope() != 0:
        raise UnsupportedStructure("charged or isotopically modified atoms are not supported yet")
    if phosphorus.GetDegree() > 3:
        raise UnsupportedStructure("a phosphorus atom with more than three substituents is not a phosphane")

    for atom in mol.GetAtoms():
        if atom.GetAtomicNum() not in (15, 6):
            raise UnsupportedStructure(
                "heteroatoms other than the phosphane phosphorus itself are "
                "not supported yet (see P-68)"
            )
        if atom.GetFormalCharge() != 0 or atom.GetIsotope() != 0:
            raise UnsupportedStructure("charged or isotopically modified atoms are not supported yet")
        if atom.GetAtomicNum() == 6 and atom.GetIsAromatic():
            raise UnsupportedStructure("an aromatic substituent (e.g. phenylphosphane) is out of scope")
    if mol.GetRingInfo().NumRings() != 0:
        raise UnsupportedStructure("a ring anywhere in the molecule is out of scope for this module")
    if non_single_bonds(mol):
        raise UnsupportedStructure(
            "an unsaturated substituent is out of scope for this module (see P-68)"
        )
    if len(Chem.GetMolFrags(mol)) > 1:
        raise UnsupportedStructure("multi-fragment structures are not supported yet")

    graph = adjacency(mol)
    substituent_names = []
    for root in graph[phosphorus.GetIdx()]:
        length = linear_branch(graph, root, phosphorus.GetIdx())
        if length is None:
            raise UnsupportedStructure(
                "a branched substituent is out of scope for this module (see P-68)"
            )
        substituent_names.append(alkyl_name(length))
    return substituent_names


def _format_mononuclear_prefixes(names) -> str:
    """Format substituent prefixes for a mononuclear parent hydride
    (locants always omitted, P-14.3.4.2(a)): a single repeated name uses an
    ordinary multiplying prefix with no parentheses; two or more different
    names, each cited exactly once, each get parenthesized except the
    alphabetically first (P-16.5.1.3.1, see module docstring). A mix of a
    multiply-cited name with a different one is out of scope (see module
    docstring) and raises `UnsupportedStructure`."""
    counts = {}
    for name in names:
        counts[name] = counts.get(name, 0) + 1
    if len(counts) == 1:
        (name, count), = counts.items()
        return multiplying_prefix(count) + name if count > 1 else name

    if any(count > 1 for count in counts.values()):
        raise UnsupportedStructure(
            "a multiply-cited substituent mixed with a different one is not "
            "supported yet (see P-68)"
        )
    ordered = sorted(counts, key=alpha_sort_key)
    parts = [ordered[0]] + [f"({name})" for name in ordered[1:]]
    return "".join(parts)


def name_simple_phosphane(mol) -> str:
    substituent_names = _validate_and_collect_substituents(mol)
    if not substituent_names:
        return "phosphane"
    return _format_mononuclear_prefixes(substituent_names) + "phosphane"
