"""Naming of simple phosphanes (PH3 bearing 1-3 unbranched, saturated alkyl
and/or plain phenyl substituents), per the IUPAC 2013 Recommendations
("the Blue Book"):

- P-68 (Chapter P-6, https://iupac.qmul.ac.uk/BlueBook/PDF/P6.pdf):
  unlike amines (`_amine.py`, where a carbon chain is the parent hydride
  and -NH2 is cited as a suffix, e.g. "ethanamine"), a phosphane's parent
  hydride is the phosphorus atom itself (PH3, "phosphane"); alkyl groups
  are cited as substituent prefixes in a purely substitutive name, e.g.
  "methylphosphane" (not an amine-style "methanophosphine"). Confirmed via
  PubChem PUG REST: CID 68973 (`CP`) -> "methylphosphane", CID 69607
  (`CPC`) -> "dimethylphosphane", CID 136382 (`CCP`) -> "ethylphosphane",
  CID 68983 (`CP(C)C`) -> "trimethylphosphane", CID 27365
  (`CCP(CC)CC`) -> "triethylphosphane".
- P-14.3.4.2(a): phosphorus is the sole skeletal atom of the parent
  hydride, so every substituent's locant is always '1' and is never cited
  -- mirroring `_amine.py`'s/`_silane_chain.py`'s own mononuclear-parent
  locant omission, reused here via `format_substituent_prefixes`'s
  `omit_locants=True` mode.
- P-16.5.1.3.1 (per the Blue Book's own published errata,
  https://iupac.qmul.ac.uk/bibliog/BBerrors.html, correcting the original
  text's "butyl(ethyl)methyl(propyl)silane" to
  "butyl(ethyl)(methyl)(propyl)silane"): when two or more *different*
  substituent prefixes are cited without locants on a mononuclear parent,
  the first (alphabetically) is never parenthesized, but every subsequent
  one is -- even a plain simple substituent that would otherwise never be
  parenthesized (`format_substituent_prefixes` in `_substituents.py` only
  parenthesizes a "compound"/nested substituent, so that shared helper
  doesn't implement this locant-omission-specific rule; this module has
  its own formatter instead). Confirmed via PubChem for the two-different-
  substituent case: CID 20221924 (`CCPC`) -> "ethyl(methyl)phosphane", not
  "ethylmethylphosphane". For three different substituents, PubChem's own
  autogenerated name (`CCP(C)CCC` -> "ethyl-methyl-propylphosphane") does
  NOT follow this rule (a known gap in its naming engine, not usable as a
  cross-check here) -- the errata's rule text is applied directly instead,
  giving "ethyl(methyl)(propyl)phosphane".
- Multiple *identical* substituents use the ordinary multiplying prefix
  (di-, tri-) with no parentheses at all (P-16.5.1.3.1 doesn't apply --
  there's only one distinct substituent name to cite), e.g.
  "dimethylphosphane", "trimethylphosphane".
- A multiply-cited substituent mixed with a different one combines both
  rules above rather than needing a new one: each distinct name still gets
  its own multiplying prefix by count, and the alphabetically-first
  distinct name is still the only one never parenthesized (P-16.5.1.3.1),
  regardless of its own count -- but the multiplying prefix itself
  always sits *outside* the parentheses (P-16.5.1.3.1's own text, "the
  multiplicative prefixes are not included in the parentheses"),
  confirmed directly via the Blue Book's own "ethyldi(methyl)phosphane
  (PIN)" worked example (`tmp/bluebook/P1.html`) -- a correction from
  this module's own earlier (PubChem-trusted) assumption
  ("ethyl(dimethyl)phosphane" for CID 535207's structure, another
  instance of PubChem's own parenthesization unreliability, same as the
  branched-substituent note below): "ethyl(methyl x2)" is now
  "ethyldi(methyl)phosphane", and "ethyl x2 + methyl x1" (CID 13836128)
  stays "diethyl(methyl)phosphane" unchanged (the multiplied group was
  already first, so it was never wrapped in the first place).

- A halogen (F/Cl/Br/I) bonded directly to phosphorus is just another
  substituent prefix that already fits the P-16.5.1.3.1 parenthesization
  rule above (no new mechanism needed) -- confirmed via PubChem PUG REST
  for structure only: CID 161938 (`ClP`) -> "chlorophosphane", CID
  13128761 (`ClPCl`) -> "dichlorophosphane"; CID 69936's structure
  (`ClP(C)C`) is named "chlorodi(methyl)phosphane" here (not PubChem's
  own raw "chloro(dimethyl)phosphane"), matching the Blue Book's own
  "chlorodi(methyl)borane (PIN)" worked example for the analogous
  borane case (`tmp/bluebook/P6.txt`).

- A branched substituent is supported (e.g. 'propan-2-ylphosphane',
  PubChem CID 537979; 'tert-butylphosphane', CID 123165), built with
  `name_branch`. A lone compound (branched) name is not parenthesized
  when it's the only substituent (P-16.5.1.3.2's "second and subsequent"
  framing), but as soon as there's a second, different substituent to
  cite, a compound first substituent *does* get its own parentheses too
  -- '(propan-2-yl)(propyl)phosphane', not PubChem's own raw
  'propan-2-yl(propyl)phosphane' (CID 85572629) -- per P-16.5.1.3.1's
  literal text ("the first cited substituent never has enclosing marks
  unless it is a compound substituent group or includes a locant," see
  `tmp/bluebook/P1.html`); see `format_mononuclear_prefixes`'s own
  docstring for the full derivation, including the multiplied case (e.g.
  'tri(propan-2-yl)phosphane', CID 80969, independently confirmed via the
  Blue Book's own 'ethyldi(propan-2-yl)silane (PIN)' worked example). A
  multiplied compound name mixed with a *different* substituent is out of
  scope (unconfirmed punctuation, see that same docstring).
- A plain, unsubstituted benzene ring bonded directly to phosphorus is
  cited as a 'phenyl' substituent, mixed freely with alkyl/halogen
  substituents -- confirmed via PubChem PUG REST: `c1ccccc1P` ->
  "phenylphosphane" (CID 12519), `c1ccccc1P(c1ccccc1)c1ccccc1` ->
  "triphenylphosphane" (CID 11776). Like `_borane.py`'s identical
  extension and unlike `_phosphanone.py`'s (P=O, PR #395), phosphorus's
  normal valence here is exactly 3, so three phenyl substituents never
  trigger a lambda-convention label. Detection reuses the same
  `_plain_phenyl_substituent_atoms` pattern (`is_plain_benzene_ring` +
  `ring_chain_attachment`) adapted for phosphorus's own direct-neighbor
  substituent roots.

Explicitly out of scope (raise `UnsupportedStructure`):
- Any atom other than phosphorus, carbon, hydrogen, and a halogen bonded
  directly to phosphorus (no P=O, no halogen-substituted alkyl chain, no
  other heteroatom in a substituent chain).
- More than one phosphorus atom (phosphane chains, e.g. diphosphane --
  `_silane_chain.py`-style "chain" nomenclature is a separate problem).
- An unsaturated substituent, an aromatic substituent other than a plain,
  unsubstituted phenyl (a substituted or heteroaromatic ring, e.g.), or a
  ring other than a plain phenyl substituent directly on phosphorus.
- Charged or isotopically modified atoms.
"""

from rdkit import Chem

from ._common import (
    HALOGEN_PREFIXES,
    UnsupportedStructure,
    adjacency,
    is_plain_benzene_ring,
    non_single_bonds,
    ring_chain_attachment,
)
from ._substituents import format_mononuclear_prefixes, name_branch


def has_simple_phosphane_shape(mol) -> bool:
    return any(atom.GetAtomicNum() == 15 for atom in mol.GetAtoms())


def _plain_phenyl_substituent_atoms(mol, graph, roots):
    """Union of ring atoms for every plain, unsubstituted benzene ring in
    `mol` that hangs directly off one of `roots` (the phosphane
    phosphorus's own substituent neighbors) with no other exocyclic
    attachment -- i.e. a lone 'phenyl' substituent directly on phosphorus.
    Mirrors `_borane.py`'s identical helper (itself mirroring
    `_phosphanone.py`'s/`_carbamate.py`'s), adapted for a plain phosphane
    in place of boron/phosphanone."""
    atoms = set()
    for ring in mol.GetRingInfo().AtomRings():
        ring_atoms = set(ring)
        if not is_plain_benzene_ring(mol, ring_atoms):
            continue
        attachment = ring_chain_attachment(graph, ring_atoms, set())
        if attachment is None:
            continue
        ring_atom, _ = attachment
        if ring_atom in roots:
            atoms |= ring_atoms
    return atoms


def _validate_and_collect_substituents(mol):
    phosphorus_atoms = [atom for atom in mol.GetAtoms() if atom.GetAtomicNum() == 15]
    if len(phosphorus_atoms) != 1:
        raise UnsupportedStructure(
            "more than one phosphorus atom is not supported yet (see P-68, "
            "phosphane chain nomenclature is a separate problem)"
        )
    (phosphorus,) = phosphorus_atoms
    if phosphorus.GetFormalCharge() != 0 or phosphorus.GetIsotope() != 0:
        raise UnsupportedStructure("charged or isotopically modified atoms are not supported yet")
    if phosphorus.GetDegree() > 3:
        raise UnsupportedStructure("a phosphorus atom with more than three substituents is not a phosphane")

    graph = adjacency(mol)
    roots = set(graph[phosphorus.GetIdx()])
    phenyl_atoms = _plain_phenyl_substituent_atoms(mol, graph, roots)

    for atom in mol.GetAtoms():
        is_halogen = atom.GetAtomicNum() in HALOGEN_PREFIXES
        if atom.GetAtomicNum() not in (15, 6) and not is_halogen:
            raise UnsupportedStructure(
                "heteroatoms other than the phosphane phosphorus itself are "
                "not supported yet (see P-68)"
            )
        if is_halogen and (
            atom.GetDegree() != 1 or atom.GetNeighbors()[0].GetIdx() != phosphorus.GetIdx()
        ):
            raise UnsupportedStructure(
                "a halogen-substituted alkyl chain is out of scope for this "
                "module -- only a halogen bonded directly to phosphorus is "
                "supported so far"
            )
        if atom.GetFormalCharge() != 0 or atom.GetIsotope() != 0:
            raise UnsupportedStructure("charged or isotopically modified atoms are not supported yet")
        if atom.GetAtomicNum() == 6 and atom.GetIsAromatic() and atom.GetIdx() not in phenyl_atoms:
            raise UnsupportedStructure(
                "an aromatic substituent other than a plain, unsubstituted "
                "phenyl group is out of scope for this module"
            )
    all_ring_atoms = {a for ring in mol.GetRingInfo().AtomRings() for a in ring}
    if all_ring_atoms - phenyl_atoms:
        raise UnsupportedStructure(
            "a ring other than a plain phenyl substituent directly on "
            "phosphorus is out of scope for this module"
        )
    non_ring_unsaturation = [
        b for b in non_single_bonds(mol) if b[0] not in phenyl_atoms and b[1] not in phenyl_atoms
    ]
    if non_ring_unsaturation:
        raise UnsupportedStructure(
            "an unsaturated substituent is out of scope for this module "
            "(see P-68)"
        )
    if len(Chem.GetMolFrags(mol)) > 1:
        raise UnsupportedStructure("multi-fragment structures are not supported yet")

    substituent_names = []
    for root in roots:
        if root in phenyl_atoms:
            substituent_names.append(("phenyl", False))
            continue
        root_atomic_num = mol.GetAtomWithIdx(root).GetAtomicNum()
        if root_atomic_num in HALOGEN_PREFIXES:
            substituent_names.append((HALOGEN_PREFIXES[root_atomic_num], False))
            continue
        substituent_names.append(name_branch(graph, root, phosphorus.GetIdx(), {}))
    return substituent_names


def name_simple_phosphane(mol) -> str:
    substituent_names = _validate_and_collect_substituents(mol)
    if not substituent_names:
        return "phosphane"
    return format_mononuclear_prefixes(substituent_names) + "phosphane"
