"""Naming of simple phosphanes (PH3 bearing 1-5 unbranched, saturated alkyl
and/or plain phenyl substituents -- four or five triggering the P-14.1
λ-convention, #1018), per the IUPAC 2013 Recommendations ("the Blue
Book"):

- P-68 (Chapter P-6, https://iupac.qmul.ac.uk/BlueBook/PDF/P6.pdf):
  unlike amines (`_amine.py`, where a carbon chain is the parent hydride
  and -NH2 is cited as a suffix, e.g. "ethanamine"), a phosphane's parent
  hydride is the phosphorus atom itself (PH3, "phosphane"); alkyl groups
  are cited as substituent prefixes in a purely substitutive name, e.g.
  "methylphosphane" (not an amine-style "methanophosphine"). Confirmed via
  PubChem PUG REST: CID 68973 (`CP`) -> "methylphosphane", CID 69607
  (`CPC`) -> "dimethylphosphane", CID 136382 (`CCP`) -> "ethylphosphane",
  CID 68983 (`CP(C)C`) -> "trimethylphosphane", CID 27365
  (`CCP(CC)CC`) -> "triethylphosphane".
- P-14.3.4.2(a): phosphorus is the sole skeletal atom of the parent
  hydride, so every substituent's locant is always '1' and is never cited
  -- mirroring `_amine.py`'s/`_silane_chain.py`'s own mononuclear-parent
  locant omission, reused here via `format_substituent_prefixes`'s
  `omit_locants=True` mode.
- P-16.5.1.3.1 (per the Blue Book's own published errata,
  https://iupac.qmul.ac.uk/bibliog/BBerrors.html, correcting the original
  text's "butyl(ethyl)methyl(propyl)silane" to
  "butyl(ethyl)(methyl)(propyl)silane"): when two or more *different*
  substituent prefixes are cited without locants on a mononuclear parent,
  the first (alphabetically) is never parenthesized, but every subsequent
  one is -- even a plain simple substituent that would otherwise never be
  parenthesized (`format_substituent_prefixes` in `_substituents.py` only
  parenthesizes a "compound"/nested substituent, so that shared helper
  doesn't implement this locant-omission-specific rule; this module has
  its own formatter instead). Confirmed via PubChem for the two-different-
  substituent case: CID 20221924 (`CCPC`) -> "ethyl(methyl)phosphane", not
  "ethylmethylphosphane". For three different substituents, PubChem's own
  autogenerated name (`CCP(C)CCC` -> "ethyl-methyl-propylphosphane") does
  NOT follow this rule (a known gap in its naming engine, not usable as a
  cross-check here) -- the errata's rule text is applied directly instead,
  giving "ethyl(methyl)(propyl)phosphane".
- Multiple *identical* substituents use the ordinary multiplying prefix
  (di-, tri-) with no parentheses at all (P-16.5.1.3.1 doesn't apply --
  there's only one distinct substituent name to cite), e.g.
  "dimethylphosphane", "trimethylphosphane".
- A multiply-cited substituent mixed with a different one combines both
  rules above rather than needing a new one: each distinct name still gets
  its own multiplying prefix by count, and the alphabetically-first
  distinct name is still the only one never parenthesized (P-16.5.1.3.1),
  regardless of its own count -- but the multiplying prefix itself
  always sits *outside* the parentheses (P-16.5.1.3.1's own text, "the
  multiplicative prefixes are not included in the parentheses"),
  confirmed directly via the Blue Book's own "ethyldi(methyl)phosphane
  (PIN)" worked example (`tmp/bluebook/P1.html`) -- a correction from
  this module's own earlier (PubChem-trusted) assumption
  ("ethyl(dimethyl)phosphane" for CID 535207's structure, another
  instance of PubChem's own parenthesization unreliability, same as the
  branched-substituent note below): "ethyl(methyl x2)" is now
  "ethyldi(methyl)phosphane", and "ethyl x2 + methyl x1" (CID 13836128)
  stays "diethyl(methyl)phosphane" unchanged (the multiplied group was
  already first, so it was never wrapped in the first place).

- A halogen (F/Cl/Br/I) bonded directly to phosphorus is just another
  substituent prefix that already fits the P-16.5.1.3.1 parenthesization
  rule above (no new mechanism needed) -- confirmed via PubChem PUG REST
  for structure only: CID 161938 (`ClP`) -> "chlorophosphane", CID
  13128761 (`ClPCl`) -> "dichlorophosphane"; CID 69936's structure
  (`ClP(C)C`) is named "chlorodi(methyl)phosphane" here (not PubChem's
  own raw "chloro(dimethyl)phosphane"), matching the Blue Book's own
  "chlorodi(methyl)borane (PIN)" worked example for the analogous
  borane case (`tmp/bluebook/P6.txt`).

- A branched substituent is supported (e.g. 'propan-2-ylphosphane',
  PubChem CID 537979; 'tert-butylphosphane', CID 123165), built with
  `name_branch`. A lone compound (branched) name is not parenthesized
  when it's the only substituent (P-16.5.1.3.2's "second and subsequent"
  framing), but as soon as there's a second, different substituent to
  cite, a compound first substituent *does* get its own parentheses too
  -- '(propan-2-yl)(propyl)phosphane', not PubChem's own raw
  'propan-2-yl(propyl)phosphane' (CID 85572629) -- per P-16.5.1.3.1's
  literal text ("the first cited substituent never has enclosing marks
  unless it is a compound substituent group or includes a locant," see
  `tmp/bluebook/P1.html`); see `format_mononuclear_prefixes`'s own
  docstring for the full derivation, including the multiplied case (e.g.
  'tri(propan-2-yl)phosphane', CID 80969, independently confirmed via the
  Blue Book's own 'ethyldi(propan-2-yl)silane (PIN)' worked example). A
  multiplied compound name mixed with a *different* substituent is out of
  scope (unconfirmed punctuation, see that same docstring).
- A plain, unsubstituted benzene ring bonded directly to phosphorus is
  cited as a 'phenyl' substituent, mixed freely with alkyl/halogen
  substituents -- confirmed via PubChem PUG REST: `c1ccccc1P` ->
  "phenylphosphane" (CID 12519), `c1ccccc1P(c1ccccc1)c1ccccc1` ->
  "triphenylphosphane" (CID 11776). Like `_borane.py`'s identical
  extension and unlike `_phosphanone.py`'s (P=O, PR #395), phosphorus's
  normal valence here is exactly 3, so three phenyl substituents never
  trigger a lambda-convention label. Detection reuses the same
  `plain_phenyl_substituent_atoms` pattern (`is_plain_benzene_ring` +
  `ring_chain_attachment`) adapted for phosphorus's own direct-neighbor
  substituent roots.
- A benzene ring bonded directly to phosphorus and also bearing one or
  more halogen substituents of its own is cited as a halogenated-phenyl
  substituent, e.g. '(4-chlorophenyl)phosphane' -- confirmed via PubChem
  PUG REST: `Clc1ccc(cc1)P` -> "(4-chlorophenyl)phosphane" (CID 17762777),
  `Clc1ccccc1P` -> "(2-chlorophenyl)phosphane" (CID 17796935),
  `Fc1ccc(cc1)P` -> "(4-fluorophenyl)phosphane" (CID 17762775),
  `Brc1ccc(cc1)P` -> "(4-bromophenyl)phosphane" (CID 23413207),
  `Clc1ccc(Cl)c(Cl)c1P` -> "(2,3,6-trichlorophenyl)phosphane" (CID
  160229181, multiple halogens on one ring, lowest-locants direction
  chosen per P-14.5.2), and three identical rings ->
  "tris(4-chlorophenyl)phosphane" (CID 70874). Unlike a branched alkyl
  compound name (e.g. 'propan-2-yl'), this kind of name -- a *substituted*
  substituent group -- both needs enclosing marks even as the sole
  substituent and takes the 'bis'/'tris' multiplying series rather than
  ordinary 'di'/'tri' (P-14.2.2); detected here by the name's own leading
  locant digit (`format_mononuclear_prefixes`'s own docstring has the
  full derivation). Mixing a halogenated-phenyl substituent with any
  differently-named substituent (plain phenyl, a lone halogen, an alkyl
  group, or a *different* halogenated phenyl) is out of scope: PubChem's
  own raw name for the halophenyl+alkyl case
  ('(4-chlorophenyl)-methylphosphane') doesn't follow the already-
  established P-16.5.1.3.1 parenthesization rule (contrast
  'ethyl(methyl)phosphane'), and two different halogenated-phenyl rings on
  one phosphorus aren't registered in PubChem at all (CID 0) -- so neither
  is trusted. Ring groups are named by `_hydride_ring_groups.hydride_ring_groups`
  (shared with `_borane.py`).
- The λ-convention (P-14.1, #1018): four or five substituents (a bonding
  number of 5, since RDKit's own default valence model for neutral
  phosphorus fills any unwritten valence to the nearest of {3, 5}, never
  stopping at 4 for a plain SMILES with no bracket atom -- confirmed:
  `CP(C)(C)(C)C`, four explicit substituents with no bracket notation,
  parses with `GetTotalValence() == 5`) exceeds the normal bonding number
  of 3, so a 'λ5-' label is inserted directly before 'phosphane' --
  mirrors `_phosphanone.py`'s identical mechanism for the P=O case, and
  confirmed directly by the Blue Book's own worked example (P-14.1.3):
  '(C6H5)3PH2 -> triphenyl-λ5-phosphane (PIN)'. A bonding number of
  exactly 4 is not handled: the only reachable SMILES shape for it
  (explicit bracket notation forcing valence 4 on a neutral phosphorus,
  e.g. `[PH](C)(C)C`) is a genuine phosphoranyl radical (1 unpaired
  electron, confirmed via `GetNumRadicalElectrons()`), not a closed-shell
  phosphane at all -- already routed to `_radical.py` by `core.py`'s
  dispatch before this module is ever reached, so no real input can reach
  this module with `GetTotalValence() == 4`.

Explicitly out of scope (raise `UnsupportedStructure`):
- Any atom other than phosphorus, carbon, hydrogen, and a halogen bonded
  directly to phosphorus or to a halogenated-phenyl ring on phosphorus (no
  P=O, no halogen-substituted alkyl chain, no other heteroatom in a
  substituent chain).
- More than one phosphorus atom (phosphane chains, e.g. diphosphane --
  `_silane_chain.py`-style "chain" nomenclature is a separate problem).
- An unsaturated substituent, an aromatic substituent other than a plain
  or halogen-substituted phenyl (a substituted-by-something-else or
  heteroaromatic ring, e.g.), or a ring other than that directly on
  phosphorus.
- A halogenated-phenyl substituent mixed with a differently-named
  substituent (see above).
- Charged or isotopically modified atoms.
"""

from rdkit import Chem

from ._common import (
    HALOGEN_PREFIXES,
    UnsupportedStructure,
    adjacency,
    non_single_bonds,
    plain_phenyl_substituent_atoms,
)
from ._hydride_ring_groups import hydride_ring_groups
from ._substituents import format_mononuclear_prefixes, name_branch


def has_simple_phosphane_shape(mol) -> bool:
    return any(atom.GetAtomicNum() == 15 for atom in mol.GetAtoms())


def _validate_and_collect_substituents(mol):
    phosphorus_atoms = [atom for atom in mol.GetAtoms() if atom.GetAtomicNum() == 15]
    if len(phosphorus_atoms) != 1:
        raise UnsupportedStructure(
            "more than one phosphorus atom is not supported yet (see P-68, "
            "phosphane chain nomenclature is a separate problem)"
        )
    (phosphorus,) = phosphorus_atoms
    if phosphorus.GetFormalCharge() != 0 or phosphorus.GetIsotope() != 0:
        raise UnsupportedStructure("charged or isotopically modified atoms are not supported yet")

    graph = adjacency(mol)
    roots = set(graph[phosphorus.GetIdx()])
    phenyl_atoms = plain_phenyl_substituent_atoms(mol, graph, roots)

    ring_groups = hydride_ring_groups(mol, graph, roots - phenyl_atoms, phosphorus.GetIdx())
    group_atoms = {a for _, _, atoms in ring_groups.values() for a in atoms}

    for atom in mol.GetAtoms():
        idx = atom.GetIdx()
        if idx in group_atoms:
            continue
        is_halogen = atom.GetAtomicNum() in HALOGEN_PREFIXES
        if atom.GetAtomicNum() not in (15, 6) and not is_halogen:
            raise UnsupportedStructure(
                "heteroatoms other than the phosphane phosphorus itself are "
                "not supported yet (see P-68)"
            )
        if is_halogen and (
            atom.GetDegree() != 1 or atom.GetNeighbors()[0].GetIdx() != phosphorus.GetIdx()
        ):
            raise UnsupportedStructure(
                "a halogen-substituted alkyl chain is out of scope for this "
                "module -- only a halogen bonded directly to phosphorus, or "
                "to a phenyl ring directly on phosphorus, is supported so far"
            )
        if atom.GetFormalCharge() != 0 or atom.GetIsotope() != 0:
            raise UnsupportedStructure("charged or isotopically modified atoms are not supported yet")
        if (
            atom.GetAtomicNum() == 6
            and atom.GetIsAromatic()
            and idx not in phenyl_atoms
            and idx not in group_atoms
        ):
            raise UnsupportedStructure(
                "an aromatic substituent other than a plain or halogen-"
                "substituted phenyl group is out of scope for this module"
            )
    all_ring_atoms = {a for ring in mol.GetRingInfo().AtomRings() for a in ring}
    if all_ring_atoms - phenyl_atoms - group_atoms:
        raise UnsupportedStructure(
            "a ring other than a plain or halogen-substituted phenyl "
            "substituent directly on phosphorus is out of scope for this "
            "module"
        )
    non_ring_unsaturation = [
        b
        for b in non_single_bonds(mol)
        if b[0] not in phenyl_atoms
        and b[1] not in phenyl_atoms
        and b[0] not in group_atoms
        and b[1] not in group_atoms
    ]
    if non_ring_unsaturation:
        raise UnsupportedStructure(
            "an unsaturated substituent is out of scope for this module "
            "(see P-68)"
        )
    if len(Chem.GetMolFrags(mol)) > 1:
        raise UnsupportedStructure("multi-fragment structures are not supported yet")

    substituent_names = []
    for root in roots:
        if root in phenyl_atoms:
            substituent_names.append(("phenyl", False))
            continue
        if root in ring_groups:
            name, compound, _ = ring_groups[root]
            substituent_names.append((name, compound))
            continue
        root_atomic_num = mol.GetAtomWithIdx(root).GetAtomicNum()
        if root_atomic_num in HALOGEN_PREFIXES:
            substituent_names.append((HALOGEN_PREFIXES[root_atomic_num], False))
            continue
        substituent_names.append(name_branch(graph, root, phosphorus.GetIdx(), {}, mol=mol))

    distinct_names = {name for name, _ in substituent_names}
    if len(distinct_names) > 1 and any(
        is_compound and name[0].isdigit() for name, is_compound in substituent_names
    ):
        raise UnsupportedStructure(
            "a halogen-substituted phenyl group mixed with any differently-"
            "named substituent is out of scope for this module -- the "
            "resulting punctuation isn't confirmed by PubChem (unregistered "
            "for two different halogenated phenyls on the same phosphorus) "
            "or a Blue Book worked example (PubChem's raw "
            "'(4-chlorophenyl)-methylphosphane' for the halophenyl+alkyl "
            "case leaves the non-first plain substituent unparenthesized, "
            "unlike the already-established 'ethyl(methyl)phosphane' "
            "precedent, so it isn't trusted blind either)"
        )
    return substituent_names


def name_simple_phosphane(mol) -> str:
    substituent_names = _validate_and_collect_substituents(mol)
    (phosphorus,) = [atom for atom in mol.GetAtoms() if atom.GetAtomicNum() == 15]
    valence = phosphorus.GetTotalValence()
    # A neutral, non-radical phosphorus is only ever trivalent or
    # pentavalent (P-14.1) -- a bonding number of 4 has no valid neutral
    # closed-shell Lewis structure (confirmed: the only reachable SMILES
    # shape for it, e.g. "[PH](C)(C)C", is a genuine phosphoranyl radical,
    # already routed to `_radical.py` before this module is ever reached
    # -- see #1018), so it's not handled here.
    if valence not in (3, 5):
        raise UnsupportedStructure(f"a phosphorus bonding number of {valence} is not supported yet")
    parent = f"λ{valence}-phosphane" if valence == 5 else "phosphane"
    if not substituent_names:
        return parent
    prefix = format_mononuclear_prefixes(substituent_names)
    return f"{prefix}-{parent}" if valence == 5 else prefix + parent
